#include <stdio.h>

// Function to calculate the nth Fibonacci number
int fibonacci(int n) { 
    // Base case: If n is 0 or 1, return n
    if (n <= 1)
        return n;

    // Recursive case: Calculate the Fibonacci number using recursion
    return fibonacci(n - 1) + fibonacci(n - 2);
}

int main() {
    int n;
    printf("Enter the range: ");
    scanf("%d", &n);

    printf("Fibonacci Series: ");
    for (int i = 0; i < n; i++) {
        printf("%d ", fibonacci(i));
    }

    return 0;
}

/* DRY RUN



Let's use an example where n is 6 to understand how the code works.

The user is prompted to enter the range, and they enter 6.

The main function calls fibonacci(0) to fibonacci(5) in a loop.

fibonacci(0) is called first:

Since n is 0, it hits the base case: return 0.
fibonacci(1) is called next:

Since n is 1, it also hits the base case: return 1.
fibonacci(2) is called:

It's not a base case, so it calculates fibonacci(1) + fibonacci(0) which is 1 + 0 = 1.
fibonacci(3) is called:

It calculates fibonacci(2) + fibonacci(1) which is 1 + 1 = 2.
fibonacci(4) is called:

It calculates fibonacci(3) + fibonacci(2) which is 2 + 1 = 3.
fibonacci(5) is called:

It calculates fibonacci(4) + fibonacci(3) which is 3 + 2 = 5.
The loop in the main function iterates from i = 0 to i = 5, printing the Fibonacci numbers generated by fibonacci(0) to fibonacci(5).

The output is: "Fibonacci Series: 0 1 1 2 3 5".



*/
